# Generated by Django 2.1 on 2020-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='leiras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
